### ISSUE TITLE
Added functionality to load and run a trained model in CartPole environment

### ISSUE THREAD

**Issue by Yonom1** [NotFish232/CartPole#1]
Hi NotFish232,

I want to let you know that I’ve added functionality to your code to load and run a pre-trained model. After training, I was able to save the model as trained.pt and load it later to evaluate the agent’s performance in the CartPole environment without retraining.

I believe this feature could be helpful for others who would like to load and directly test their trained models.

If you allow, I would like to upload these changes to the repository so others can benefit from them as well.

Thanks for the great code!

Best regards,
Yonom1

**Comment by NotFish232** [comment]
Hi Yonom1,

Thanks for the kind words. That functionality sounds great! If you want to contribute that or any other feature please make a pull request and I'll be happy to review it! Thanks.

Best,
NotFish232

**Comment by Yonom1** [comment]
> Hi Yonom1,
> 
> Thanks for the kind words. That functionality sounds great! If you want to contribute that or any other feature please make a pull request and I'll be happy to review it! Thanks.
> 
> Best, NotFish232

Dear NotFish232,

Thank you for your recognition and acceptance!

Best regards,
Yonom1
